net: wireless: bcmdhd: Remove unused variables
../drivers/net/wireless/bcmdhd/dhd_rtt.c:207:33: error: unused variable
'ftm_tlvid_loginfo' [-Werror,-Wunused-const-variable]

../drivers/net/wireless/bcmdhd/dhd_rtt.c:295:33: error: unused variable
'ftm_ranging_state_value_loginfo' [-Werror,-Wunused-const-variable]

Change-Id: I565bc4a3935381e3dddee57cac2f4b4f33910a21
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>